### ISSUE TITLE
!AIABM messages not being decoded

### ISSUE THREAD

**Issue by TwinTurbine** [chrisadie/node-red-contrib-ais-decoder#30] opened 2023-11-19 20:38 UTC
Hi Chris,

After having tried out the Message 12 support it seems to me that the decoding of the free text portion doesn't really work for "all kinds" of type 12 messages. The following message:

```
!AIABM,2,1,0,000023534,0,12,lsoks00L;>t5OTqjghIwmaww3:D5CDPD5HDP10B5@1LdVLq,0*5E
!AIABM,2,2,0,,,,3nwv=1@Phi10B5@1Go<M6;Vwv=1@Phj,0*1D
```
should decode to:

`4;73;@@\KN<E_$92/0Y?5)??CJTEST TEXT A@REPA\,&\9C6?>MAP 01A@REPAW7L]FK&?>MAP 02`

but for some reason I get the following error message:

`errorInfo: "Wrong number of fields in fragment"`

Even though the message starts with AIABM instead of AIVDM it doesn't complain about the checksum so there seems to be something else going on that I'm unable to figure out.

If you do have the time to have a look at it I would be very grateful.

Regards,

**Comment by chrisadie** [comment] 2023-11-21 13:35
I have reproduced this.

The problem is that the code has not been written to decode !AIABM messages. It only works with !AIVDM and !AIVDO messages, which all contain seven fields in each fragment. The example !AIABM message above contains nine fields.

I'm happy to adapt the code (within reason) to recognise !AIABM messages IF I can find a description of these messages. So far, I've not been able to find anything. Do you have a reference document which would help?

**Comment by TwinTurbine** [comment] 2023-11-22 08:49
You're absolutely correct. I failed to identify the field differences. However, there will no need to rewrite anything to accompany the !AIABM structure since this is only a "local" serial structure for transfer to the AIS transponder itself. I don't have any reference documents (yet) but the !AIABM sentence is then repacked by the AIS transponder into the Message 12 format before transmission. So it will be revceived as an Addressed Safety Related Message. But for now I only have this example of a message before being handled by the AIS transponder. It might not be of any use, however.

The current ais decoder seems to get most of the decoding right, including the message lenght, but instead of outputting `4;57;@@` for instance, it will output `4;57;  `; double blankspaces instead of double `@` at the end. 

Using the ais decoder with the following message:

`!AIVDM,2,1,1,A,<000960JQih@lsmos00Q;>t9Dd:9GiL>eaww38231jihhP058;@im10B,0*18`
`!AIVDM,2,2,1,A,5@2E;2REtFwv=1@Phi0,2*17`

will yield this string:

`4;57;  !KN<IT,JIW1\N-)??CHBCA2100  EHKP15A REPBUKB"U<V?>MAP 01`

When it should be decoded as the following instead:

`4;57;@@!KN<IT,JIW1\N-)??CHBCA2100 @EHKP15A@REPBUKB"U<V?>MAP 01`

So not all of the blankspaces should be translated into `@` chars, but some of them. Do you think it would be possible to identify why both blankspaces and `@` chars are translated into only blankspaces in the decoding? 

The online Maritec AIS decoder will handle the `@` chars correctly but doesn't decode the whole string, probably because of not being able to handle the "escape characters" without interpreting them as such.

So, to me it seems that the current decoder version is very close to perfect as it is. Hopefully there's only a slight "tweak" missing. :-)

**Comment by chrisadie** [comment] 2023-11-22 14:07
> So not all of the blankspaces should be translated into @ chars, but some of them. 

You're right. I will open another issue for this. I'll close this one.

**Comment by chrisadie** [comment] 2023-11-22 14:08
No plans to decode !AIABM messages.

**Closed as completed** 2023-11-22 14:10 UTC
